#!/data/data/com.termux/files/usr/bin/bash

DIR=$HOME/PocoMiner

clear

echo "=============================="
echo "       POCO X5 LTC MINER"
echo "=============================="
echo

echo "1. Start Mining LTC"
echo "2. Start Mining XMR"
echo "3. Stop Mining"
echo "4. Monitor"
echo "5. Status"
echo "6. Exit"
echo

read -p "Choose : " menu

case $menu in

1)
cd $DIR
./start_ltc.sh
;;

2)
cd $DIR
./start_xmr.sh
;;

3)
cd $DIR
./stop_ltc.sh
;;

4)
cd $DIR

if pgrep -f xmrig >/dev/null
then
    echo "Miner : RUNNING"
    echo

    if pgrep -af xmrig | grep -q "config_xmr.json"
    then
        ./monitor_xmr.sh
    else
        ./monitor_ltc.sh
    fi
else
    echo "Miner : STOPPED"
fi
;;

5)
echo
echo "===== STATUS MINER ====="
echo

if pgrep -f xmrig >/dev/null
then
    echo "Miner : RUNNING"
    echo

    echo "Process:"
    pgrep -af xmrig

    echo

    if pgrep -af xmrig | grep -q "config_xmr.json"
    then
        echo "Mining : XMR"

        if [ -f $DIR/miner_xmr.log ]
        then
            echo
            echo "Latest XMR Log:"
            tail -10 $DIR/miner_xmr.log
        fi

    else
        echo "Mining : LTC"

        if [ -f $DIR/miner_ltc.log ]
        then
            echo
            echo "Latest LTC Log:"
            tail -10 $DIR/miner_ltc.log
        fi
    fi

else
    echo "Miner : STOPPED"
fi

echo
read -p "Tekan Enter..."
;;


5)
exit
;;

*)
echo "Pilihan salah"
;;

esac
